"""file model."""

from enum import StrEnum
from typing import TYPE_CHECKING

from sqlalchemy import (
	BigInteger,
	ForeignKey,
	Index,
	String,
	Text,
	inspect,
	text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from api.models.base import TYPEID_LENGTH, Base, StringEnum
from api.models.many_to_many import file_project_association
from api.models.mixins import (
	MetadataJSONMixin,
	OriginMessageMixin,
	SoftDeleteMixin,
	TimestampMixin,
	TypeIDPrimaryKeyMixin,
)
from nokodo_ai.utils.typeid import TypeID


if TYPE_CHECKING:
	from api.models.access_rule import AccessRule
	from api.models.message import Message
	from api.models.project import Project
	from api.models.user import User


class FileSource(StrEnum):
	"""how a file entered the system, and what it is."""

	USER_UPLOADED = "user_uploaded"
	AGENT_GENERATED = "agent_generated"
	USER_IMPORTED = "user_imported"
	TEXT_EXTRACTION = "text_extraction"
	THUMBNAIL = "thumbnail"


class FileStatus(StrEnum):
	"""Lifecycle status for a file pointer."""

	PENDING = "pending"
	AVAILABLE = "available"


class File(
	TypeIDPrimaryKeyMixin,
	TimestampMixin,
	MetadataJSONMixin,
	OriginMessageMixin,
	SoftDeleteMixin,
	Base,
):
	"""First-class record pointing to uploaded or generated bytes in storage."""

	__tablename__ = "files"
	__typeid_prefix__ = "file"
	__table_args__ = (
		Index(
			"idx_files_filename_trgm",
			"filename",
			postgresql_using="gin",
			postgresql_ops={"filename": "gin_trgm_ops"},
		),
		Index(
			"idx_files_description_trgm",
			"description",
			postgresql_using="gin",
			postgresql_ops={"description": "gin_trgm_ops"},
		),
		Index(
			"ix_files_parent_file_id",
			"parent_file_id",
			postgresql_where=text("parent_file_id IS NOT NULL"),
		),
	)

	# null on internal derivatives
	owner_id: Mapped[TypeID | None] = mapped_column(
		String(TYPEID_LENGTH),
		ForeignKey("users.id"),
		index=True,
	)

	source: Mapped[FileSource] = mapped_column(
		StringEnum(FileSource),
		default=FileSource.USER_UPLOADED,
	)
	storage_backend: Mapped[str] = mapped_column(String(50))
	storage_key: Mapped[str] = mapped_column(String(1024), unique=True)
	filename: Mapped[str | None] = mapped_column(String(255))
	mime_type: Mapped[str | None] = mapped_column(String(255))
	size_bytes: Mapped[int | None] = mapped_column(BigInteger())
	checksum_sha256: Mapped[str | None] = mapped_column(String(64))
	description: Mapped[str | None] = mapped_column(Text, nullable=True)
	status: Mapped[FileStatus] = mapped_column(
		StringEnum(FileStatus),
		default=FileStatus.PENDING,
	)

	# the user file an internal derivative was derived from; null on user files.
	parent_file_id: Mapped[TypeID | None] = mapped_column(
		String(TYPEID_LENGTH),
		ForeignKey(
			"files.id",
			ondelete="CASCADE",
			use_alter=True,
			name="files_parent_file_id_fkey",
		),
	)

	owner: Mapped[User | None] = relationship(
		"User",
		back_populates="files",
	)
	projects: Mapped[list[Project]] = relationship(
		"Project",
		secondary=file_project_association,
		back_populates="files",
	)

	@property
	def project_ids(self) -> list[TypeID]:
		"""IDs of linked projects (requires projects to be loaded)."""
		return [p.id for p in self.projects]

	@property
	def origin_thread_id(self) -> TypeID | None:
		"""thread id resolved through the linked origin message when loaded."""
		if self.origin_message_id is None or "origin_message" in inspect(self).unloaded:
			return None
		return self.origin_message.thread_id if self.origin_message else None

	origin_message: Mapped[Message | None] = relationship(
		"Message",
		foreign_keys="File.origin_message_id",
	)
	access_rules: Mapped[list[AccessRule]] = relationship(
		"AccessRule",
		back_populates="file",
		cascade="all, delete-orphan",
	)
