"""File model."""

from __future__ import annotations

from enum import StrEnum
from typing import TYPE_CHECKING

from sqlalchemy import BigInteger, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from api.models.base import TYPEID_LENGTH, Base, StringEnum
from api.models.mixins import (
	MetadataJSONMixin,
	SoftDeleteMixin,
	TimestampMixin,
	TypeIDPrimaryKeyMixin,
)


if TYPE_CHECKING:
	from api.models.access_rule import AccessRule
	from api.models.message import Message
	from api.models.project import Project
	from api.models.user import User


class FileSource(StrEnum):
	"""How a file entered the system."""

	UPLOAD = "upload"
	GENERATED = "generated"
	IMPORT = "import"


class FileStatus(StrEnum):
	"""Lifecycle status for a file pointer."""

	PENDING = "pending"
	AVAILABLE = "available"


class File(
	TypeIDPrimaryKeyMixin,
	TimestampMixin,
	MetadataJSONMixin,
	SoftDeleteMixin,
	Base,
):
	"""First-class record pointing to uploaded or generated bytes in storage."""

	__tablename__ = "files"
	__typeid_prefix__ = "file"

	owner_id: Mapped[str] = mapped_column(
		String(TYPEID_LENGTH),
		ForeignKey("users.id"),
		index=True,
	)

	source: Mapped[FileSource] = mapped_column(
		StringEnum(FileSource),
		default=FileSource.UPLOAD,
	)
	storage_backend: Mapped[str] = mapped_column(String(50))
	storage_key: Mapped[str] = mapped_column(String(1024))
	filename: Mapped[str | None] = mapped_column(String(255))
	mime_type: Mapped[str | None] = mapped_column(String(255))
	size_bytes: Mapped[int | None] = mapped_column(BigInteger())
	checksum_sha256: Mapped[str | None] = mapped_column(String(64))
	description: Mapped[str | None] = mapped_column(Text, nullable=True)
	status: Mapped[FileStatus] = mapped_column(
		StringEnum(FileStatus),
		default=FileStatus.PENDING,
	)

	project_id: Mapped[str | None] = mapped_column(
		String(TYPEID_LENGTH),
		ForeignKey("projects.id", ondelete="SET NULL"),
		index=True,
	)
	message_id: Mapped[str | None] = mapped_column(
		String(TYPEID_LENGTH),
		ForeignKey("messages.id", ondelete="SET NULL"),
		index=True,
	)

	owner: Mapped[User] = relationship(
		"User",
		back_populates="files",
		innerjoin=True,
	)
	project: Mapped[Project | None] = relationship(
		"Project",
		back_populates="files",
	)
	message: Mapped[Message | None] = relationship(
		"Message",
		back_populates="files",
	)
	access_rules: Mapped[list[AccessRule]] = relationship(
		"AccessRule",
		back_populates="file",
		cascade="all, delete-orphan",
	)
