"""file model."""

from __future__ import annotations

from enum import StrEnum
from typing import TYPE_CHECKING

from sqlalchemy import BigInteger, ForeignKey, Index, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from api.models.base import TYPEID_LENGTH, Base, StringEnum
from api.models.many_to_many import file_project_association
from api.models.mixins import (
	MetadataJSONMixin,
	SoftDeleteMixin,
	TimestampMixin,
	TypeIDPrimaryKeyMixin,
)
from nokodo_ai.utils.typeid import TypeID


if TYPE_CHECKING:
	from api.models.access_rule import AccessRule
	from api.models.message import Message
	from api.models.project import Project
	from api.models.user import User


class FileSource(StrEnum):
	"""How a file entered the system."""

	UPLOAD = "upload"
	GENERATED = "generated"
	IMPORT = "import"


class FileStatus(StrEnum):
	"""Lifecycle status for a file pointer."""

	PENDING = "pending"
	AVAILABLE = "available"


class File(
	TypeIDPrimaryKeyMixin,
	TimestampMixin,
	MetadataJSONMixin,
	SoftDeleteMixin,
	Base,
):
	"""First-class record pointing to uploaded or generated bytes in storage."""

	__tablename__ = "files"
	__typeid_prefix__ = "file"
	__table_args__ = (
		Index(
			"idx_files_filename_trgm",
			"filename",
			postgresql_using="gin",
			postgresql_ops={"filename": "gin_trgm_ops"},
		),
		Index(
			"idx_files_description_trgm",
			"description",
			postgresql_using="gin",
			postgresql_ops={"description": "gin_trgm_ops"},
		),
	)

	owner_id: Mapped[str] = mapped_column(
		String(TYPEID_LENGTH),
		ForeignKey("users.id"),
		index=True,
	)

	source: Mapped[FileSource] = mapped_column(
		StringEnum(FileSource),
		default=FileSource.UPLOAD,
	)
	storage_backend: Mapped[str] = mapped_column(String(50))
	storage_key: Mapped[str] = mapped_column(String(1024))
	filename: Mapped[str | None] = mapped_column(String(255))
	mime_type: Mapped[str | None] = mapped_column(String(255))
	size_bytes: Mapped[int | None] = mapped_column(BigInteger())
	checksum_sha256: Mapped[str | None] = mapped_column(String(64))
	description: Mapped[str | None] = mapped_column(Text, nullable=True)
	status: Mapped[FileStatus] = mapped_column(
		StringEnum(FileStatus),
		default=FileStatus.PENDING,
	)

	message_id: Mapped[str | None] = mapped_column(
		String(TYPEID_LENGTH),
		ForeignKey(
			"messages.id",
			ondelete="SET NULL",
			use_alter=True,
			name="files_message_id_fkey",
		),
		index=True,
	)

	owner: Mapped[User] = relationship(
		"User",
		back_populates="files",
		innerjoin=True,
	)
	projects: Mapped[list[Project]] = relationship(
		"Project",
		secondary=file_project_association,
		back_populates="files",
	)

	@property
	def project_ids(self) -> list[TypeID]:
		"""IDs of linked projects (requires projects to be loaded)."""
		return [p.id for p in self.projects]

	message: Mapped[Message | None] = relationship(
		"Message",
		back_populates="files",
	)
	access_rules: Mapped[list[AccessRule]] = relationship(
		"AccessRule",
		back_populates="file",
		cascade="all, delete-orphan",
	)
