"""add_missing_provider_columns

Revision ID: 1db9b6b7f242
Revises: 81a0d8ef2ad9
Create Date: 2025-12-08 05:26:00.879389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db9b6b7f242'
down_revision = '81a0d8ef2ad9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_prefix', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('additional_headers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_column('additional_headers')
        batch_op.drop_column('model_prefix')

    # ### end Alembic commands ###
