version: 2
updates:
  # backend dependencies
  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend"
    groups:
      backend-all:
        patterns:
          - "*"

  # frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "frontend"
    groups:
      frontend-all:
        patterns:
          - "*"

  # console dependencies
  - package-ecosystem: "npm"
    directory: "/console"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "console"
    groups:
      console-all:
        patterns:
          - "*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci/cd"
    groups:
      github-actions-all:
        patterns:
          - "*"

  # Docker
  - package-ecosystem: "docker"
    directory: "/.docker"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "containerization"
    groups:
      docker-all:
        patterns:
          - "*"
