# github: add up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# patreon: add a single Patreon username
# open_collective: add a single Open Collective username
ko_fi: nokodo
# buy_me_a_coffee: add your Buy Me a Coffee username
