blank_issues_enabled: true
contact_links:
  - name: 📧 contact maintainers
    url: https://nokodo.net/about
    about: get in touch with the nokodo team
  - name: 💬 discussions
    url: https://github.com/nokodo-labs/monorepo-template/discussions
    about: ask questions and discuss ideas with the community
  - name: 📚 documentation
    url: https://github.com/nokodo-labs/monorepo-template/wiki
    about: access the project's documentation
  - name: 🚀 releases
    url: https://github.com/nokodo-labs/monorepo-template/releases
    about: view the project's releases
