/**
 * Icon Components
 *
 * All icons with solid variants support a `variant` prop:
 * - `variant="outline"` (default)
 * - `variant="solid"`
 *
 * @example
 * import { Plus, Search, Sparkles } from '$lib/components/icons';
 *
 * // outline (default)
 * <Sparkles />
 *
 * // solid variant
 * <Sparkles variant="solid" />
 *
 * // with custom color
 * <Sparkles color="#ff0000" />
 */

export { default as AdjustmentsHorizontal } from './AdjustmentsHorizontal.svelte'
export { default as AdjustmentsHorizontalOutline } from './AdjustmentsHorizontalOutline.svelte'
export { default as Agile } from './Agile.svelte'
export { default as AlignHorizontal } from './AlignHorizontal.svelte'
export { default as AlignVertical } from './AlignVertical.svelte'
export { default as AppNotification } from './AppNotification.svelte'
export { default as ArchiveBox } from './ArchiveBox.svelte'
export { default as ArrowLeft } from './ArrowLeft.svelte'
export { default as ArrowLeftTag } from './ArrowLeftTag.svelte'
export { default as ArrowPath } from './ArrowPath.svelte'
export { default as ArrowRight } from './ArrowRight.svelte'
export { default as ArrowRightCircle } from './ArrowRightCircle.svelte'
export { default as ArrowRightTag } from './ArrowRightTag.svelte'
export { default as ArrowsPointingOut } from './ArrowsPointingOut.svelte'
export { default as ArrowTurnDownRight } from './ArrowTurnDownRight.svelte'
export { default as ArrowUpCircle } from './ArrowUpCircle.svelte'
export { default as ArrowUpLeft } from './ArrowUpLeft.svelte'
export { default as ArrowUpLeftAlt } from './ArrowUpLeftAlt.svelte'
export { default as ArrowUpTray } from './ArrowUpTray.svelte'
export { default as ArrowUturnLeft } from './ArrowUturnLeft.svelte'
export { default as ArrowUturnRight } from './ArrowUturnRight.svelte'
export { default as Bars3BottomLeft } from './Bars3BottomLeft.svelte'
export { default as BarsArrowUp } from './BarsArrowUp.svelte'
export { default as Bold } from './Bold.svelte'
export { default as Bolt } from './Bolt.svelte'
export { default as Bookmark } from './Bookmark.svelte'
export { default as BookmarkSlash } from './BookmarkSlash.svelte'
export { default as BookOpen } from './BookOpen.svelte'
export { default as Calendar } from './Calendar.svelte'
export { default as Camera } from './Camera.svelte'
export { default as ChartBar } from './ChartBar.svelte'
export { default as ChatBubble } from './ChatBubble.svelte'
export { default as ChatBubbleDotted } from './ChatBubbleDotted.svelte'
export { default as ChatBubbleDottedChecked } from './ChatBubbleDottedChecked.svelte'
export { default as ChatBubbleOval } from './ChatBubbleOval.svelte'
export { default as ChatBubbles } from './ChatBubbles.svelte'
export { default as ChatCheck } from './ChatCheck.svelte'
export { default as ChatPlus } from './ChatPlus.svelte'
export { default as Check } from './Check.svelte'
export { default as CheckBox } from './CheckBox.svelte'
export { default as CheckCircle } from './CheckCircle.svelte'
export { default as ChevronDown } from './ChevronDown.svelte'
export { default as ChevronLeft } from './ChevronLeft.svelte'
export { default as ChevronRight } from './ChevronRight.svelte'
export { default as ChevronUp } from './ChevronUp.svelte'
export { default as ChevronUpDown } from './ChevronUpDown.svelte'
export { default as Clip } from './Clip.svelte'
export { default as Clipboard } from './Clipboard.svelte'
export { default as ClockRotateRight } from './ClockRotateRight.svelte'
export { default as Cloud } from './Cloud.svelte'
export { default as CloudArrowUp } from './CloudArrowUp.svelte'
export { default as Code } from './Code.svelte'
export { default as CodeBracket } from './CodeBracket.svelte'
export { default as Cog6 } from './Cog6.svelte'
export { default as CommandLine } from './CommandLine.svelte'
export { default as Component } from './Component.svelte'
export { default as Computer } from './Computer.svelte'
export { default as Cube } from './Cube.svelte'
export { default as CursorArrowRays } from './CursorArrowRays.svelte'
export { default as Database } from './Database.svelte'
export { default as DatabaseSettings } from './DatabaseSettings.svelte'
export { default as Document } from './Document.svelte'
export { default as DocumentArrowDown } from './DocumentArrowDown.svelte'
export { default as DocumentArrowUp } from './DocumentArrowUp.svelte'
export { default as DocumentChartBar } from './DocumentChartBar.svelte'
export { default as DocumentCheck } from './DocumentCheck.svelte'
export { default as DocumentDuplicate } from './DocumentDuplicate.svelte'
export { default as DocumentPage } from './DocumentPage.svelte'
export { default as Download } from './Download.svelte'
export { default as EllipsisHorizontal } from './EllipsisHorizontal.svelte'
export { default as EllipsisVertical } from './EllipsisVertical.svelte'
export { default as Eye } from './Eye.svelte'
export { default as EyeSlash } from './EyeSlash.svelte'
export { default as Face } from './Face.svelte'
export { default as FaceId } from './FaceId.svelte'
export { default as FaceSmile } from './FaceSmile.svelte'
export { default as FloppyDisk } from './FloppyDisk.svelte'
export { default as Folder } from './Folder.svelte'
export { default as FolderOpen } from './FolderOpen.svelte'
export { default as GarbageBin } from './GarbageBin.svelte'
export { default as Github } from './Github.svelte'
export { default as Glasses } from './Glasses.svelte'
export { default as GlobeAlt } from './GlobeAlt.svelte'
export { default as Grid } from './Grid.svelte'
export { default as H1 } from './H1.svelte'
export { default as H2 } from './H2.svelte'
export { default as H3 } from './H3.svelte'
export { default as Hashtag } from './Hashtag.svelte'
export { default as Headphone } from './Headphone.svelte'
export { default as Heart } from './Heart.svelte'
export { default as Home } from './Home.svelte'
export { default as Info } from './Info.svelte'
export { default as InfoCircle } from './InfoCircle.svelte'
export { default as Italic } from './Italic.svelte'
export { default as Keyboard } from './Keyboard.svelte'
export { default as Knobs } from './Knobs.svelte'
export { default as Label } from './Label.svelte'
export { default as Lifebuoy } from './Lifebuoy.svelte'
export { default as LightBulb } from './LightBulb.svelte'
export { default as LineSpace } from './LineSpace.svelte'
export { default as LineSpaceSmaller } from './LineSpaceSmaller.svelte'
export { default as Link } from './Link.svelte'
export { default as ListBullet } from './ListBullet.svelte'
export { default as Lock } from './Lock.svelte'
export { default as LockClosed } from './LockClosed.svelte'
export { default as Map } from './Map.svelte'
export { default as MenuLines } from './MenuLines.svelte'
export { default as Merge } from './Merge.svelte'
export { default as Mic } from './Mic.svelte'
export { default as Minus } from './Minus.svelte'
export { default as Note } from './Note.svelte'
export { default as NumberedList } from './NumberedList.svelte'
export { default as PageEdit } from './PageEdit.svelte'
export { default as Pencil } from './Pencil.svelte'
export { default as PencilSquare } from './PencilSquare.svelte'
export { default as PeopleTag } from './PeopleTag.svelte'
export { default as Photo } from './Photo.svelte'
export { default as PinSlash } from './PinSlash.svelte'
export { default as Plus } from './Plus.svelte'
export { default as PlusAlt } from './PlusAlt.svelte'
export { default as QuestionMarkCircle } from './QuestionMarkCircle.svelte'
export { default as QueueList } from './QueueList.svelte'
export { default as Refresh } from './Refresh.svelte'
export { default as Reset } from './Reset.svelte'
export { default as Search } from './Search.svelte'
export { default as Settings } from './Settings.svelte'
export { default as SettingsAlt } from './SettingsAlt.svelte'
export { default as Share } from './Share.svelte'
export { default as Sidebar } from './Sidebar.svelte'
export { default as SignOut } from './SignOut.svelte'
export { default as SoundHigh } from './SoundHigh.svelte'
export { default as Sparkles } from './Sparkles.svelte'
export { default as Star } from './Star.svelte'
export { default as Strikethrough } from './Strikethrough.svelte'
export { default as Tag } from './Tag.svelte'
export { default as Terminal } from './Terminal.svelte'
export { default as Underline } from './Underline.svelte'
export { default as Union } from './Union.svelte'
export { default as User } from './User.svelte'
export { default as UserBadgeCheck } from './UserBadgeCheck.svelte'
export { default as UserCircle } from './UserCircle.svelte'
export { default as UserGroup } from './UserGroup.svelte'
export { default as UserPlusSolid } from './UserPlusSolid.svelte'
export { default as Users } from './Users.svelte'
export { default as Voice } from './Voice.svelte'
export { default as WifiSlash } from './WifiSlash.svelte'
export { default as Wrench } from './Wrench.svelte'
export { default as WrenchAlt } from './WrenchAlt.svelte'
export { default as XMark } from './XMark.svelte'
export { default as Youtube } from './Youtube.svelte'
