/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get System Status
         * @description Check system initialization status.
         */
        get: operations["get_system_status_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/access-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Access Token
         * @description OAuth2 compatible token login, get an access token for future requests.
         */
        post: operations["login_access_token_auth_login_access_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Users
         * @description Retrieve users.
         */
        get: operations["read_users_users_get"];
        put?: never;
        /**
         * Create User
         * @description Create new user.
         */
        post: operations["create_user_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read User
         * @description Get user by ID (future permissions will restrict visibility).
         */
        get: operations["read_user_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Threads
         * @description List threads optionally filtered by owner.
         */
        get: operations["list_threads_threads_get"];
        put?: never;
        /**
         * Create Thread
         * @description Create a new thread.
         */
        post: operations["create_thread_threads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Thread
         * @description Fetch a single thread with messages.
         */
        get: operations["get_thread_threads__thread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Thread
         * @description Update thread metadata.
         */
        patch: operations["update_thread_threads__thread_id__patch"];
        trace?: never;
    };
    "/threads/{thread_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description List messages within a thread.
         */
        get: operations["list_messages_threads__thread_id__messages_get"];
        put?: never;
        /**
         * Create Message
         * @description Append a message to a thread.
         */
        post: operations["create_message_threads__thread_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tasks
         * @description List tasks with optional filters.
         */
        get: operations["list_tasks_tasks_get"];
        put?: never;
        /**
         * Create Task
         * @description Create a new task.
         */
        post: operations["create_task_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Task
         * @description Update mutable task fields.
         */
        patch: operations["update_task_tasks__task_id__patch"];
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Query events with flexible filters.
         */
        get: operations["list_events_events_get"];
        put?: never;
        /**
         * Emit Event
         * @description Persist and broadcast an event.
         */
        post: operations["emit_event_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List User Notifications
         * @description Return notifications for a user.
         */
        get: operations["list_user_notifications_notifications_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Notification Read
         * @description Mark a notification as read.
         */
        post: operations["mark_notification_read_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss Notification
         * @description Dismiss a notification without marking it read.
         */
        post: operations["dismiss_notification_notifications__notification_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Memories
         * @description List memories for a user.
         */
        get: operations["list_memories_memories_get"];
        put?: never;
        /**
         * Create Memory
         * @description Capture a new memory.
         */
        post: operations["create_memory_memories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Memory
         * @description Fetch a single memory.
         */
        get: operations["get_memory_memories__memory_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Providers
         * @description List configured providers.
         */
        get: operations["list_providers_providers_get"];
        put?: never;
        /**
         * Create Provider
         * @description Register a provider.
         */
        post: operations["create_provider_providers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Provider
         * @description Fetch a provider.
         */
        get: operations["get_provider_providers__provider_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Provider
         * @description Update provider fields.
         */
        patch: operations["update_provider_providers__provider_id__patch"];
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description List models with optional provider filter.
         */
        get: operations["list_models_models_get"];
        put?: never;
        /**
         * Create Model
         * @description Register a model for a provider.
         */
        post: operations["create_model_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model
         * @description Fetch a single model.
         */
        get: operations["get_model_models__model_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Agents
         * @description List all agents.
         */
        get: operations["list_agents_agents_get"];
        put?: never;
        /**
         * Create Agent
         * @description Register a new agent.
         */
        post: operations["create_agent_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent
         * @description Fetch an agent.
         */
        get: operations["get_agent_agents__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Agent
         * @description Response schema.
         */
        Agent: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** System Prompt */
            system_prompt?: string | null;
            /** @default public */
            visibility: components["schemas"]["AgentVisibility"];
            /** Tool Ids */
            tool_ids?: string[];
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /** Model Id */
            model_id?: string | null;
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            model?: components["schemas"]["Model"] | null;
        };
        /**
         * AgentCreate
         * @description Payload for agent creation.
         */
        AgentCreate: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** System Prompt */
            system_prompt?: string | null;
            /** @default public */
            visibility: components["schemas"]["AgentVisibility"];
            /** Tool Ids */
            tool_ids?: string[];
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /** Model Id */
            model_id?: string | null;
        };
        /**
         * AgentVisibility
         * @description Controls who can view an agent.
         * @enum {string}
         */
        AgentVisibility: "public" | "private" | "admin-only";
        /** Body_login_access_token_auth_login_access_token_post */
        Body_login_access_token_auth_login_access_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * Event
         * @description Event response.
         */
        Event: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** @default system */
            scope: components["schemas"]["EventScope"];
            /** Scope Id */
            scope_id?: string | null;
            /** Type */
            type: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /** Expires At */
            expires_at?: string | null;
            /**
             * Version
             * @default 1
             */
            version: number;
            /** User Id */
            user_id?: number | null;
            /** Thread Id */
            thread_id?: string | null;
            /** Message Id */
            message_id?: string | null;
            /** Task Id */
            task_id?: string | null;
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EventCreate
         * @description Payload to emit a new event.
         */
        EventCreate: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** @default system */
            scope: components["schemas"]["EventScope"];
            /** Scope Id */
            scope_id?: string | null;
            /** Type */
            type: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /** Expires At */
            expires_at?: string | null;
            /**
             * Version
             * @default 1
             */
            version: number;
            /** User Id */
            user_id?: number | null;
            /** Thread Id */
            thread_id?: string | null;
            /** Message Id */
            message_id?: string | null;
            /** Task Id */
            task_id?: string | null;
        };
        /**
         * EventScope
         * @description Domain scopes for events.
         * @enum {string}
         */
        EventScope: "system" | "user" | "thread" | "message" | "task" | "project";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Memory
         * @description Response schema.
         */
        Memory: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** Content */
            content: string;
            /** Source Message Id */
            source_message_id?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Category */
            category?: string | null;
            /** Id */
            id: string;
            /** User Id */
            user_id: number;
            /** Embedding */
            embedding?: string | null;
            /** Last Accessed At */
            last_accessed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            owner?: components["schemas"]["User"] | null;
        };
        /**
         * MemoryCreate
         * @description Payload to capture a memory.
         */
        MemoryCreate: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** Content */
            content: string;
            /** Source Message Id */
            source_message_id?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Category */
            category?: string | null;
            /** User Id */
            user_id: number;
        };
        /**
         * Message
         * @description Response schema.
         */
        Message: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** @default user */
            type: components["schemas"]["MessageType"];
            /** Content */
            content: string;
            /** Attachments */
            attachments?: {
                [key: string]: unknown;
            }[];
            /** Tool Calls */
            tool_calls?: {
                [key: string]: unknown;
            }[];
            /** Token Usage */
            token_usage?: {
                [key: string]: unknown;
            } | null;
            /** Read By */
            read_by?: number[];
            /** Id */
            id: string;
            /** Thread Id */
            thread_id: string;
            /** Task Id */
            task_id?: string | null;
            /** Sender Agent Id */
            sender_agent_id?: string | null;
            /** Sender User Id */
            sender_user_id?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * MessageCreate
         * @description Payload for creating a message within a thread.
         */
        MessageCreate: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** @default user */
            type: components["schemas"]["MessageType"];
            /** Content */
            content: string;
            /** Attachments */
            attachments?: {
                [key: string]: unknown;
            }[];
            /** Tool Calls */
            tool_calls?: {
                [key: string]: unknown;
            }[];
            /** Token Usage */
            token_usage?: {
                [key: string]: unknown;
            } | null;
            /** Read By */
            read_by?: number[];
            /** Task Id */
            task_id?: string | null;
            /** Sender Agent Id */
            sender_agent_id?: string | null;
            /** Sender User Id */
            sender_user_id?: number | null;
        };
        /**
         * MessageType
         * @description Available message types.
         * @enum {string}
         */
        MessageType: "user" | "assistant" | "tool" | "system";
        /**
         * Model
         * @description Response schema.
         */
        Model: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Display Name */
            display_name?: string | null;
            /** @default llm */
            model_type: components["schemas"]["ModelType"];
            /** Endpoint */
            endpoint?: string | null;
            /** Capabilities */
            capabilities?: string[];
            /** Context Window */
            context_window?: number | null;
            /** Input Cost */
            input_cost?: number | null;
            /** Output Cost */
            output_cost?: number | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Is Autofetched
             * @default false
             */
            is_autofetched: boolean;
            /** Id */
            id: string;
            /** Provider Id */
            provider_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ModelCreate
         * @description Payload to register a model.
         */
        ModelCreate: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Display Name */
            display_name?: string | null;
            /** @default llm */
            model_type: components["schemas"]["ModelType"];
            /** Endpoint */
            endpoint?: string | null;
            /** Capabilities */
            capabilities?: string[];
            /** Context Window */
            context_window?: number | null;
            /** Input Cost */
            input_cost?: number | null;
            /** Output Cost */
            output_cost?: number | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Is Autofetched
             * @default false
             */
            is_autofetched: boolean;
            /** Provider Id */
            provider_id: string;
        };
        /**
         * ModelType
         * @description Supported model categories.
         * @enum {string}
         */
        ModelType: "llm" | "embedding" | "image_generation" | "audio" | "video";
        /**
         * Notification
         * @description Response schema.
         */
        Notification: {
            /** User Id */
            user_id: number;
            /** Event Id */
            event_id: string;
            /**
             * Dismissed
             * @default false
             */
            dismissed: boolean;
            /** Id */
            id: string;
            /** Read At */
            read_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            event?: components["schemas"]["Event"] | null;
        };
        /**
         * Project
         * @description Project schema.
         */
        Project: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /** Owner Id */
            owner_id: number;
            /** Thread Ids */
            thread_ids?: string[];
        };
        /**
         * Provider
         * @description Response schema.
         */
        Provider: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Adapter Type */
            adapter_type: string;
            /** @default external */
            provider_type: components["schemas"]["ProviderType"];
            /** Base Url */
            base_url?: string | null;
            /** Encrypted Api Key */
            encrypted_api_key?: string | null;
            /** Model Prefix */
            model_prefix?: string | null;
            /** Additional Headers */
            additional_headers?: {
                [key: string]: string;
            } | null;
            /** @default enabled */
            status: components["schemas"]["ProviderStatus"];
            /**
             * Is Autofetch Enabled
             * @default true
             */
            is_autofetch_enabled: boolean;
            /** Last Synced At */
            last_synced_at?: string | null;
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProviderCreate
         * @description Payload to create a provider.
         */
        ProviderCreate: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Adapter Type */
            adapter_type: string;
            /** @default external */
            provider_type: components["schemas"]["ProviderType"];
            /** Base Url */
            base_url?: string | null;
            /** Encrypted Api Key */
            encrypted_api_key?: string | null;
            /** Model Prefix */
            model_prefix?: string | null;
            /** Additional Headers */
            additional_headers?: {
                [key: string]: string;
            } | null;
            /** @default enabled */
            status: components["schemas"]["ProviderStatus"];
            /**
             * Is Autofetch Enabled
             * @default true
             */
            is_autofetch_enabled: boolean;
            /** Last Synced At */
            last_synced_at?: string | null;
            /** Api Key */
            api_key?: string | null;
        };
        /**
         * ProviderStatus
         * @description Operational state of a provider.
         * @enum {string}
         */
        ProviderStatus: "enabled" | "disabled";
        /**
         * ProviderType
         * @description Type of provider deployment.
         * @enum {string}
         */
        ProviderType: "local" | "external";
        /**
         * ProviderUpdate
         * @description Partial provider update payload.
         */
        ProviderUpdate: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** Adapter Type */
            adapter_type?: string | null;
            provider_type?: components["schemas"]["ProviderType"] | null;
            /** Base Url */
            base_url?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Encrypted Api Key */
            encrypted_api_key?: string | null;
            /** Model Prefix */
            model_prefix?: string | null;
            /** Additional Headers */
            additional_headers?: {
                [key: string]: string;
            } | null;
            status?: components["schemas"]["ProviderStatus"] | null;
            /** Is Autofetch Enabled */
            is_autofetch_enabled?: boolean | null;
            /** Last Synced At */
            last_synced_at?: string | null;
        };
        /**
         * Task
         * @description Response model.
         */
        Task: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** @default custom */
            task_type: components["schemas"]["TaskType"];
            /** @default pending */
            status: components["schemas"]["TaskStatus"];
            /** Progress */
            progress?: number | null;
            /** Stage */
            stage?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: string;
            /** User Id */
            user_id: number;
            /** Spawned Thread Id */
            spawned_thread_id?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Cancelled At */
            cancelled_at?: string | null;
            /** Last Event At */
            last_event_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TaskCreate
         * @description Payload to start a task.
         */
        TaskCreate: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** @default custom */
            task_type: components["schemas"]["TaskType"];
            /** @default pending */
            status: components["schemas"]["TaskStatus"];
            /** Progress */
            progress?: number | null;
            /** Stage */
            stage?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** User Id */
            user_id: number;
            /** Spawned Thread Id */
            spawned_thread_id?: string | null;
        };
        /**
         * TaskStatus
         * @description Lifecycle status for long-running operations.
         * @enum {string}
         */
        TaskStatus: "pending" | "running" | "complete" | "failed" | "cancelled";
        /**
         * TaskType
         * @description High-level task categories.
         * @enum {string}
         */
        TaskType: "code_session" | "research" | "image_generation" | "custom";
        /**
         * TaskUpdate
         * @description Mutable task fields for PATCH operations.
         */
        TaskUpdate: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            status?: components["schemas"]["TaskStatus"] | null;
            /** Progress */
            progress?: number | null;
            /** Stage */
            stage?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * Thread
         * @description Detailed response schema.
         */
        Thread: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** Title */
            title?: string | null;
            /** Tags */
            tags?: string[];
            /**
             * Is Archived
             * @default false
             */
            is_archived: boolean;
            /** Project Ids */
            project_ids?: string[];
            /** Id */
            id: string;
            /** Owner Id */
            owner_id: number;
            /**
             * Last Activity At
             * Format: date-time
             */
            last_activity_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            owner?: components["schemas"]["User"] | null;
            /** Messages */
            messages?: components["schemas"]["Message"][];
            /** Projects */
            projects?: components["schemas"]["Project"][];
        };
        /**
         * ThreadCreate
         * @description Payload for creating a thread.
         */
        ThreadCreate: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** Title */
            title?: string | null;
            /** Tags */
            tags?: string[];
            /**
             * Is Archived
             * @default false
             */
            is_archived: boolean;
            /** Project Ids */
            project_ids?: string[];
            /** Owner Id */
            owner_id: number;
        };
        /**
         * ThreadUpdate
         * @description Payload for updating a thread.
         */
        ThreadUpdate: {
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            };
            /** Title */
            title?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Is Archived */
            is_archived?: boolean | null;
            /** Project Ids */
            project_ids?: string[] | null;
            /** Owner Id */
            owner_id?: number | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /**
         * User
         * @description Schema for user response.
         */
        User: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /** Preferences */
            preferences?: {
                [key: string]: unknown;
            };
            /** Integration Tokens */
            integration_tokens?: {
                [key: string]: unknown;
            };
            /** Usage Quotas */
            usage_quotas?: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /** Role Id */
            role_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * UserCreate
         * @description Schema for creating a user.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /** Preferences */
            preferences?: {
                [key: string]: unknown;
            };
            /** Integration Tokens */
            integration_tokens?: {
                [key: string]: unknown;
            };
            /** Usage Quotas */
            usage_quotas?: {
                [key: string]: unknown;
            };
            /** Password */
            password: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_system_status_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    login_access_token_auth_login_access_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_access_token_auth_login_access_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_users_users_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_user_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_threads_threads_get: {
        parameters: {
            query?: {
                owner_id?: number | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_thread_threads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thread_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_thread_threads__thread_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_threads__thread_id__messages_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_message_threads__thread_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_tasks_get: {
        parameters: {
            query?: {
                user_id?: number | null;
                status_filter?: components["schemas"]["TaskStatus"] | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_events_get: {
        parameters: {
            query?: {
                scope?: components["schemas"]["EventScope"] | null;
                thread_id?: string | null;
                task_id?: string | null;
                user_id?: number | null;
                since?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    emit_event_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_user_notifications_notifications_users__user_id__get: {
        parameters: {
            query?: {
                only_unread?: boolean;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_notification_read_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_notification_notifications__notification_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memories_memories_get: {
        parameters: {
            query: {
                user_id: number;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memory"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_memory_memories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memory_memories__memory_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"][];
                };
            };
        };
    };
    create_provider_providers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provider_providers__provider_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_provider_providers__provider_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_models_get: {
        parameters: {
            query?: {
                provider_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_model_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_models__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agents_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
        };
    };
    create_agent_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
