"""autogenerate an Alembic migration from an isolated temporary database.

usage:
    uv run --project backend python tools/autogen-migration.py
    uv run --project backend python tools/autogen-migration.py --output temp/autogen.py
    uv run --project backend python tools/autogen-migration.py --check
"""

from __future__ import annotations

import argparse
import importlib.machinery
import os
import shutil
import subprocess
import sys
import uuid
from collections.abc import Sequence
from datetime import UTC, datetime
from pathlib import Path
from types import ModuleType

import psycopg
from psycopg import sql
from sqlalchemy.engine import URL, make_url


def find_repo_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / "backend" / "api" / "boot_settings.py").is_file():
            return candidate
    raise RuntimeError("could not locate repository root")


REPO_ROOT = find_repo_root(Path(__file__).resolve().parent)
BACKEND_DIR = REPO_ROOT / "backend"
BOOT_SETTINGS_PATH = BACKEND_DIR / "api" / "boot_settings.py"
ALEMBIC_INI = "api/migrations/alembic.ini"
VERSIONS_DIR = BACKEND_DIR / "api" / "migrations" / "versions"
DEFAULT_OUTPUT_DIR = REPO_ROOT / "temp" / "alembic-autogen"


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="autogenerate an Alembic revision using a disposable database",
    )
    parser.add_argument(
        "--output",
        help="where to save the generated revision file",
    )
    parser.add_argument(
        "--message",
        default="autogenerated migration",
        help="Alembic revision message",
    )
    parser.add_argument(
        "--upgrade-revision",
        default="head",
        help="revision to apply to the disposable database before autogenerate",
    )
    parser.add_argument(
        "--database-url",
        help="template app database URL; defaults to DATABASE_URL/boot settings",
    )
    parser.add_argument(
        "--admin-url",
        help="postgres maintenance database URL used to create/drop the temp database",
    )
    parser.add_argument(
        "--admin-database",
        default="postgres",
        help="maintenance database name when --admin-url is omitted",
    )
    parser.add_argument(
        "--rev-id",
        help="revision id to use for the generated file",
    )
    parser.add_argument(
        "--keep-database",
        action="store_true",
        help="do not drop the temp database after running",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="overwrite the output file if it already exists",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="check for drift only; exits 0 if clean, 1 if drift detected",
    )
    return parser.parse_args(argv)


def default_database_url() -> str:
    env_url = os.getenv("DATABASE_URL")
    if env_url:
        return env_url
    if str(BACKEND_DIR) not in sys.path:
        sys.path.insert(0, str(BACKEND_DIR))
    loader = importlib.machinery.SourceFileLoader(
        "_nokodo_boot_settings",
        str(BOOT_SETTINGS_PATH),
    )
    boot_settings_module = ModuleType(loader.name)
    loader.exec_module(boot_settings_module)
    boot_settings = getattr(boot_settings_module, "boot_settings")

    return str(getattr(boot_settings, "DATABASE_URL"))


def render_url(url: URL) -> str:
    return url.render_as_string(hide_password=False)


def sync_driver_url(url: URL) -> str:
    drivername = url.drivername.split("+")[0]
    return render_url(url.set(drivername=drivername))


def temp_database_name() -> str:
    suffix = uuid.uuid4().hex[:16]
    return f"nokodo_ai_alembic_{suffix}"


def create_database(admin_url: URL, database_name: str) -> None:
    with psycopg.connect(sync_driver_url(admin_url), autocommit=True) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                sql.SQL("CREATE DATABASE {} TEMPLATE template0 ENCODING 'UTF8'").format(
                    sql.Identifier(database_name)
                )
            )


def drop_database(admin_url: URL, database_name: str) -> None:
    with psycopg.connect(sync_driver_url(admin_url), autocommit=True) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT pg_terminate_backend(pid)
                FROM pg_stat_activity
                WHERE datname = %s AND pid <> pg_backend_pid()
                """,
                (database_name,),
            )
            cursor.execute(
                sql.SQL("DROP DATABASE IF EXISTS {}").format(
                    sql.Identifier(database_name)
                )
            )


def run_alembic(args: Sequence[str], database_url: URL) -> None:
    env = os.environ.copy()
    env["DATABASE_URL"] = render_url(database_url)
    command = [sys.executable, "-m", "alembic", "-c", ALEMBIC_INI, *args]
    result = subprocess.run(
        command,
        cwd=BACKEND_DIR,
        env=env,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.stdout:
        print(result.stdout, end="")
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)
    if result.returncode != 0:
        raise SystemExit(result.returncode)


def generated_revision_path(rev_id: str) -> Path:
    matches = sorted(VERSIONS_DIR.glob(f"*{rev_id}*.py"))
    if not matches:
        raise RuntimeError(f"could not find generated revision for rev id {rev_id}")
    if len(matches) > 1:
        raise RuntimeError(f"multiple generated revisions matched rev id {rev_id}")
    return matches[0]


def default_output_path(rev_id: str) -> Path:
    stamp = datetime.now(tz=UTC).strftime("%Y%m%d_%H%M%S")
    return DEFAULT_OUTPUT_DIR / f"{stamp}-{rev_id}_autogenerated.py"


def resolve_output_path(value: str | None, rev_id: str) -> Path:
    if value is None:
        return default_output_path(rev_id)
    path = Path(value)
    return path.resolve() if path.is_absolute() else (Path.cwd() / path).resolve()


def move_generated_revision(generated: Path, output: Path, overwrite: bool) -> None:
    if output.exists() and not overwrite:
        generated.unlink(missing_ok=True)
        raise FileExistsError(f"output already exists: {output}")
    output.parent.mkdir(parents=True, exist_ok=True)
    if generated.resolve() == output.resolve():
        return
    if output.exists():
        output.unlink()
    shutil.move(str(generated), output)


def is_noop_migration(path: Path) -> bool:
    """Return True if both upgrade() and downgrade() are empty/pass-only."""
    import ast

    tree = ast.parse(path.read_text(encoding="utf-8"))
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef):
            continue
        if node.name not in ("upgrade", "downgrade"):
            continue
        body = [
            stmt
            for stmt in node.body
            if not isinstance(stmt, (ast.Pass, ast.Expr))
            or (isinstance(stmt, ast.Expr) and not isinstance(stmt.value, ast.Constant))
        ]
        if body:
            return False
    return True


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    raw_database_url = args.database_url or default_database_url()
    database_url = make_url(raw_database_url)
    database_name = temp_database_name()
    temp_url = database_url.set(database=database_name)
    admin_url = (
        make_url(args.admin_url)
        if args.admin_url
        else database_url.set(database=args.admin_database)
    )
    rev_id = args.rev_id or uuid.uuid4().hex[:12]
    output = resolve_output_path(args.output, rev_id)

    print(f"creating temporary database {database_name}")
    create_database(admin_url, database_name)
    try:
        print(f"upgrading temporary database to {args.upgrade_revision}")
        run_alembic(["upgrade", args.upgrade_revision], temp_url)
        print(f"autogenerating revision {rev_id}")
        run_alembic(
            [
                "revision",
                "--autogenerate",
                "--rev-id",
                rev_id,
                "-m",
                args.message,
            ],
            temp_url,
        )
        generated = generated_revision_path(rev_id)

        if args.check:
            if is_noop_migration(generated):
                generated.unlink()
                print("no drift detected - models and migrations are in sync")
                return 0
            else:
                print(f"drift detected! review: {generated}")
                return 1

        move_generated_revision(generated, output, args.overwrite)
        print(f"saved generated revision to {output}")
    finally:
        if args.keep_database:
            print(f"kept temporary database {database_name}")
        else:
            print(f"dropping temporary database {database_name}")
            drop_database(admin_url, database_name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
