name: frontend CI

on:
  workflow_call:
    inputs:
      run_tests:
        description: "run tests"
        type: boolean
        required: false
        default: true
      run_lint:
        description: "run linting"
        type: boolean
        required: false
        default: true
  workflow_dispatch:
    inputs:
      run_tests:
        description: "run tests"
        type: boolean
        required: false
        default: true
      run_lint:
        description: "run linting"
        type: boolean
        required: false
        default: true

jobs:
  format:
    name: check formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: frontend/.nvmrc
          check-latest: true
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: install dependencies
        run: npm ci

      - name: check formatting
        run: npm run format

  quality:
    name: check quality on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    needs: format
    strategy:
      fail-fast: false
      matrix:
        node:
          - file
          - "25"
    continue-on-error: ${{ matrix.node != 'file' }}
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup Node from .nvmrc
        if: ${{ matrix.node == 'file' }}
        uses: actions/setup-node@v6
        with:
          node-version-file: frontend/.nvmrc
          check-latest: true
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: setup Node ${{ matrix.node }}
        if: ${{ matrix.node != 'file' }}
        uses: actions/setup-node@v6
        with:
          node-version: "${{ matrix.node }}"
          check-latest: true
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: install dependencies
        run: npm ci

      - name: lint
        if: ${{ inputs.run_lint }}
        run: npm run lint

      - name: type check
        run: npm run check

      - name: run tests
        if: ${{ inputs.run_tests }}
        run: npm run test

      - name: build
        run: npm run build
