"""add last_active_at to users

Revision ID: 9ad4bb8aa7a0
Revises: 8b2d4e6f7a9c
Create Date: 2026-02-20 06:52:00.627854

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "9ad4bb8aa7a0"
down_revision = "8b2d4e6f7a9c"
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table("users", schema=None) as batch_op:
		batch_op.add_column(
			sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True)
		)

	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table("users", schema=None) as batch_op:
		batch_op.drop_column("last_active_at")

	# ### end Alembic commands ###
