"""add notes table

Revision ID: e6a981c1b388
Revises: c7efe5c7b10d
Create Date: 2026-02-02 13:01:05.779967

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e6a981c1b388"
down_revision = "c7efe5c7b10d"
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"notes",
		sa.Column("user_id", sa.String(length=90), nullable=False),
		sa.Column("title", sa.String(length=255), nullable=False),
		sa.Column("content", sa.Text(), nullable=False),
		sa.Column("labels", sa.ARRAY(sa.String(length=50)), nullable=False),
		sa.Column("id", sa.String(length=90), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column("metadata", sa.JSON(), nullable=False),
		sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
		sa.ForeignKeyConstraint(
			["user_id"],
			["users.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	with op.batch_alter_table("notes", schema=None) as batch_op:
		batch_op.create_index(batch_op.f("ix_notes_user_id"), ["user_id"], unique=False)

	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table("notes", schema=None) as batch_op:
		batch_op.drop_index(batch_op.f("ix_notes_user_id"))

	op.drop_table("notes")
	# ### end Alembic commands ###
