"""refactor_reminders_add_reminder_lists

Revision ID: c7efe5c7b10d
Revises: 9b1f2c3d4e5a
Create Date: 2026-01-24 02:50:46.600413

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "c7efe5c7b10d"
down_revision = "9b1f2c3d4e5a"
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"reminder_lists",
		sa.Column("owner_id", sa.String(length=90), nullable=False),
		sa.Column("name", sa.String(length=100), nullable=False),
		sa.Column("description", sa.String(length=500), nullable=True),
		sa.Column("color", sa.String(length=7), nullable=True),
		sa.Column("icon", sa.String(length=50), nullable=True),
		sa.Column("position", sa.Float(), nullable=False),
		sa.Column("id", sa.String(length=90), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column("metadata", sa.JSON(), nullable=False),
		sa.ForeignKeyConstraint(
			["owner_id"],
			["users.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	with op.batch_alter_table("reminders", schema=None) as batch_op:
		batch_op.add_column(sa.Column("list_id", sa.String(length=90), nullable=True))
		batch_op.add_column(sa.Column("parent_id", sa.String(length=90), nullable=True))
		# add title as nullable first, will migrate data then make non-null
		batch_op.add_column(sa.Column("title", sa.String(length=200), nullable=True))
		batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))
		batch_op.add_column(
			sa.Column("remind_at", sa.DateTime(timezone=True), nullable=True)
		)
		batch_op.add_column(
			sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True)
		)
		batch_op.add_column(
			sa.Column("position", sa.Float(), nullable=False, server_default="0")
		)
		batch_op.add_column(
			sa.Column(
				"created_at",
				sa.DateTime(timezone=True),
				server_default=sa.text("now()"),
				nullable=False,
			)
		)
		batch_op.add_column(
			sa.Column(
				"updated_at",
				sa.DateTime(timezone=True),
				server_default=sa.text("now()"),
				nullable=False,
			)
		)
		batch_op.alter_column(
			"due_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
		)
		batch_op.alter_column(
			"recurrence",
			existing_type=sa.VARCHAR(length=50),
			type_=sa.String(length=255),
			existing_nullable=True,
		)
		batch_op.create_foreign_key(
			"reminders_parent_id_fkey",
			"reminders",
			["parent_id"],
			["id"],
		)
		batch_op.create_foreign_key(
			"reminders_list_id_fkey",
			"reminder_lists",
			["list_id"],
			["id"],
		)

	# migrate existing data: copy content to title (truncated to 200 chars)
	op.execute(
		"UPDATE reminders SET title = LEFT(content, 200) "
		"WHERE title IS NULL AND content IS NOT NULL"
	)
	op.execute("UPDATE reminders SET title = 'untitled' WHERE title IS NULL")

	# now make title non-nullable
	with op.batch_alter_table("reminders", schema=None) as batch_op:
		batch_op.alter_column("title", nullable=False)
		batch_op.drop_column("content")
		batch_op.drop_column("notification_channels")
		batch_op.drop_column("external_sync")

	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table("reminders", schema=None) as batch_op:
		batch_op.add_column(
			sa.Column(
				"external_sync",
				postgresql.JSON(astext_type=sa.Text()),
				autoincrement=False,
				nullable=True,
			)
		)
		batch_op.add_column(
			sa.Column(
				"notification_channels",
				postgresql.JSON(astext_type=sa.Text()),
				autoincrement=False,
				nullable=False,
			)
		)
		batch_op.add_column(
			sa.Column(
				"content", sa.VARCHAR(length=500), autoincrement=False, nullable=False
			)
		)
		batch_op.drop_constraint("reminders_parent_id_fkey", type_="foreignkey")
		batch_op.drop_constraint("reminders_list_id_fkey", type_="foreignkey")
		batch_op.alter_column(
			"recurrence",
			existing_type=sa.String(length=255),
			type_=sa.VARCHAR(length=50),
			existing_nullable=True,
		)
		batch_op.alter_column(
			"due_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False
		)
		batch_op.drop_column("updated_at")
		batch_op.drop_column("created_at")
		batch_op.drop_column("position")
		batch_op.drop_column("completed_at")
		batch_op.drop_column("remind_at")
		batch_op.drop_column("description")
		batch_op.drop_column("title")
		batch_op.drop_column("parent_id")
		batch_op.drop_column("list_id")

	op.drop_table("reminder_lists")
	# ### end Alembic commands ###
