"""Description

Revision ID: 874e516ae894
Revises: c76fff12fadc
Create Date: 2026-01-03 22:16:25.952410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '874e516ae894'
down_revision = 'c76fff12fadc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugins',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', api.models.base.StringEnum(), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=90), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plugins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plugins_name'), ['name'], unique=True)

    op.create_table('prompts',
    sa.Column('command', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=90), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plugin_ids', sa.JSON(), nullable=False))
        batch_op.drop_column('tool_ids')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage', sa.JSON(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.drop_column('attachments')
        batch_op.drop_column('token_usage')

    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_temporary', sa.Boolean(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_column('is_temporary')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_usage', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.alter_column('content',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('usage')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.drop_column('plugin_ids')

    op.drop_table('prompts')
    with op.batch_alter_table('plugins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugins_name'))

    op.drop_table('plugins')
    # ### end Alembic commands ###
