"""add missing indexes on events.message_id and memories.source_message_id

Revision ID: 1d0f6efb111d
Revises: 05a38fea967d
Create Date: 2026-06-06 19:54:17.491297

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "1d0f6efb111d"
down_revision = "05a38fea967d"
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table("events", schema=None) as batch_op:
		batch_op.create_index(
			batch_op.f("ix_events_message_id"), ["message_id"], unique=False
		)

	with op.batch_alter_table("memories", schema=None) as batch_op:
		batch_op.create_index(
			batch_op.f("ix_memories_source_message_id"),
			["source_message_id"],
			unique=False,
		)

	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table("memories", schema=None) as batch_op:
		batch_op.drop_index(batch_op.f("ix_memories_source_message_id"))

	with op.batch_alter_table("events", schema=None) as batch_op:
		batch_op.drop_index(batch_op.f("ix_events_message_id"))

	# ### end Alembic commands ###
