"""access_rules_roles_overhaul

Revision ID: 4a9e3a556baf
Revises: e6a981c1b388
Create Date: 2026-02-08 02:22:26.259331

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from api.models.base import StringEnum
from api.permissions import AccessLevel


# revision identifiers, used by Alembic.
revision = "4a9e3a556baf"
down_revision = "e6a981c1b388"
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"user_roles",
		sa.Column("user_id", sa.String(length=90), nullable=False),
		sa.Column("role_id", sa.String(length=90), nullable=False),
		sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
		sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("user_id", "role_id"),
	)
	op.create_table(
		"access_rules",
		sa.Column("subject_user_id", sa.String(length=90), nullable=True),
		sa.Column("subject_group_id", sa.String(length=90), nullable=True),
		sa.Column("subject_role_id", sa.String(length=90), nullable=True),
		sa.Column("level", StringEnum(AccessLevel), nullable=False),
		sa.Column("order_index", sa.Integer(), nullable=False),
		sa.Column("thread_id", sa.String(length=90), nullable=True),
		sa.Column("project_id", sa.String(length=90), nullable=True),
		sa.Column("agent_id", sa.String(length=90), nullable=True),
		sa.Column("note_id", sa.String(length=90), nullable=True),
		sa.Column("memory_id", sa.String(length=90), nullable=True),
		sa.Column("task_id", sa.String(length=90), nullable=True),
		sa.Column("file_id", sa.String(length=90), nullable=True),
		sa.Column("plugin_id", sa.String(length=90), nullable=True),
		sa.Column("prompt_id", sa.String(length=90), nullable=True),
		sa.Column("group_id", sa.String(length=90), nullable=True),
		sa.Column("id", sa.String(length=90), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column("metadata", sa.JSON(), nullable=False),
		sa.CheckConstraint(
			(
				"(CASE WHEN subject_user_id IS NULL THEN 0 ELSE 1 END + "
				"CASE WHEN subject_group_id IS NULL THEN 0 ELSE 1 END + "
				"CASE WHEN subject_role_id IS NULL THEN 0 ELSE 1 END) IN (0, 1)"
			),
			name="ck_access_rules_single_principal",
		),
		sa.CheckConstraint(
			(
				"subject_group_id IS NULL OR group_id IS NULL OR "
				"subject_group_id != group_id"
			),
			name="ck_access_rules_no_self_group",
		),
		sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
		sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
		sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
		sa.ForeignKeyConstraint(["memory_id"], ["memories.id"], ondelete="CASCADE"),
		sa.ForeignKeyConstraint(["note_id"], ["notes.id"], ondelete="CASCADE"),
		sa.ForeignKeyConstraint(["plugin_id"], ["plugins.id"], ondelete="CASCADE"),
		sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
		sa.ForeignKeyConstraint(["prompt_id"], ["prompts.id"], ondelete="CASCADE"),
		sa.ForeignKeyConstraint(
			["subject_group_id"], ["groups.id"], ondelete="CASCADE"
		),
		sa.ForeignKeyConstraint(["subject_role_id"], ["roles.id"], ondelete="CASCADE"),
		sa.ForeignKeyConstraint(["subject_user_id"], ["users.id"], ondelete="CASCADE"),
		sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
		sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint(
			"subject_user_id",
			"subject_group_id",
			"subject_role_id",
			"thread_id",
			"project_id",
			"agent_id",
			"note_id",
			"memory_id",
			"task_id",
			"file_id",
			"plugin_id",
			"prompt_id",
			"group_id",
			name="uq_access_rule_subject_resource",
		),
	)
	with op.batch_alter_table("access_rules", schema=None) as batch_op:
		batch_op.create_index(
			batch_op.f("ix_access_rules_agent_id"), ["agent_id"], unique=False
		)
		batch_op.create_index(
			batch_op.f("ix_access_rules_file_id"), ["file_id"], unique=False
		)
		batch_op.create_index(
			batch_op.f("ix_access_rules_group_id"), ["group_id"], unique=False
		)
		batch_op.create_index(
			batch_op.f("ix_access_rules_memory_id"), ["memory_id"], unique=False
		)
		batch_op.create_index(
			batch_op.f("ix_access_rules_note_id"), ["note_id"], unique=False
		)
		batch_op.create_index(
			batch_op.f("ix_access_rules_plugin_id"), ["plugin_id"], unique=False
		)
		batch_op.create_index(
			batch_op.f("ix_access_rules_project_id"), ["project_id"], unique=False
		)
		batch_op.create_index(
			batch_op.f("ix_access_rules_prompt_id"), ["prompt_id"], unique=False
		)
		batch_op.create_index(
			batch_op.f("ix_access_rules_subject_group_id"),
			["subject_group_id"],
			unique=False,
		)
		batch_op.create_index(
			batch_op.f("ix_access_rules_subject_role_id"),
			["subject_role_id"],
			unique=False,
		)
		batch_op.create_index(
			batch_op.f("ix_access_rules_subject_user_id"),
			["subject_user_id"],
			unique=False,
		)
		batch_op.create_index(
			batch_op.f("ix_access_rules_task_id"), ["task_id"], unique=False
		)
		batch_op.create_index(
			batch_op.f("ix_access_rules_thread_id"), ["thread_id"], unique=False
		)

	with op.batch_alter_table("access_control_entries", schema=None) as batch_op:
		batch_op.drop_index(batch_op.f("ix_access_control_entries_project_id"))
		batch_op.drop_index(batch_op.f("ix_access_control_entries_thread_id"))
		batch_op.drop_index(batch_op.f("ix_access_control_entries_user_id"))

	op.drop_table("access_control_entries")
	with op.batch_alter_table("roles", schema=None) as batch_op:
		batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))
		batch_op.add_column(sa.Column("default_permissions", sa.JSON(), nullable=False))
		batch_op.add_column(
			sa.Column(
				"created_at",
				sa.DateTime(timezone=True),
				server_default=sa.text("now()"),
				nullable=False,
			)
		)
		batch_op.add_column(
			sa.Column(
				"updated_at",
				sa.DateTime(timezone=True),
				server_default=sa.text("now()"),
				nullable=False,
			)
		)
		batch_op.drop_column("default_resource_access")
		batch_op.drop_column("permissions")

	with op.batch_alter_table("users", schema=None) as batch_op:
		batch_op.drop_constraint(batch_op.f("users_role_id_fkey"), type_="foreignkey")
		batch_op.drop_column("role_id")

	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table("users", schema=None) as batch_op:
		batch_op.add_column(
			sa.Column(
				"role_id", sa.VARCHAR(length=90), autoincrement=False, nullable=True
			)
		)
		batch_op.create_foreign_key(
			batch_op.f("users_role_id_fkey"), "roles", ["role_id"], ["id"]
		)

	with op.batch_alter_table("roles", schema=None) as batch_op:
		batch_op.add_column(
			sa.Column(
				"permissions",
				postgresql.JSON(astext_type=sa.Text()),
				autoincrement=False,
				nullable=False,
			)
		)
		batch_op.add_column(
			sa.Column(
				"default_resource_access",
				postgresql.JSON(astext_type=sa.Text()),
				server_default=sa.text("'{}'::json"),
				autoincrement=False,
				nullable=False,
			)
		)
		batch_op.drop_column("updated_at")
		batch_op.drop_column("created_at")
		batch_op.drop_column("default_permissions")
		batch_op.drop_column("description")

	op.create_table(
		"access_control_entries",
		sa.Column("id", sa.VARCHAR(length=90), autoincrement=False, nullable=False),
		sa.Column(
			"thread_id", sa.VARCHAR(length=90), autoincrement=False, nullable=True
		),
		sa.Column(
			"project_id", sa.VARCHAR(length=90), autoincrement=False, nullable=True
		),
		sa.Column("user_id", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
		sa.Column(
			"group_id", sa.VARCHAR(length=90), autoincrement=False, nullable=True
		),
		sa.Column(
			"agent_id", sa.VARCHAR(length=90), autoincrement=False, nullable=True
		),
		sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=False),
		sa.Column(
			"created_at",
			postgresql.TIMESTAMP(timezone=True),
			server_default=sa.text("now()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"updated_at",
			postgresql.TIMESTAMP(timezone=True),
			server_default=sa.text("now()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"metadata",
			postgresql.JSON(astext_type=sa.Text()),
			autoincrement=False,
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["agent_id"],
			["agents.id"],
			name=op.f("access_control_entries_agent_id_fkey"),
			ondelete="CASCADE",
		),
		sa.ForeignKeyConstraint(
			["group_id"],
			["groups.id"],
			name=op.f("access_control_entries_group_id_fkey"),
			ondelete="CASCADE",
		),
		sa.ForeignKeyConstraint(
			["project_id"],
			["projects.id"],
			name=op.f("access_control_entries_project_id_fkey"),
			ondelete="CASCADE",
		),
		sa.ForeignKeyConstraint(
			["thread_id"],
			["threads.id"],
			name=op.f("access_control_entries_thread_id_fkey"),
			ondelete="CASCADE",
		),
		sa.ForeignKeyConstraint(
			["user_id"],
			["users.id"],
			name=op.f("access_control_entries_user_id_fkey"),
			ondelete="CASCADE",
		),
		sa.PrimaryKeyConstraint("id", name=op.f("access_control_entries_pkey")),
	)
	with op.batch_alter_table("access_control_entries", schema=None) as batch_op:
		batch_op.create_index(
			batch_op.f("ix_access_control_entries_user_id"), ["user_id"], unique=False
		)
		batch_op.create_index(
			batch_op.f("ix_access_control_entries_thread_id"),
			["thread_id"],
			unique=False,
		)
		batch_op.create_index(
			batch_op.f("ix_access_control_entries_project_id"),
			["project_id"],
			unique=False,
		)

	with op.batch_alter_table("access_rules", schema=None) as batch_op:
		batch_op.drop_index(batch_op.f("ix_access_rules_thread_id"))
		batch_op.drop_index(batch_op.f("ix_access_rules_task_id"))
		batch_op.drop_index(batch_op.f("ix_access_rules_subject_user_id"))
		batch_op.drop_index(batch_op.f("ix_access_rules_subject_role_id"))
		batch_op.drop_index(batch_op.f("ix_access_rules_subject_group_id"))
		batch_op.drop_index(batch_op.f("ix_access_rules_prompt_id"))
		batch_op.drop_index(batch_op.f("ix_access_rules_project_id"))
		batch_op.drop_index(batch_op.f("ix_access_rules_plugin_id"))
		batch_op.drop_index(batch_op.f("ix_access_rules_note_id"))
		batch_op.drop_index(batch_op.f("ix_access_rules_memory_id"))
		batch_op.drop_index(batch_op.f("ix_access_rules_group_id"))
		batch_op.drop_index(batch_op.f("ix_access_rules_file_id"))
		batch_op.drop_index(batch_op.f("ix_access_rules_agent_id"))

	op.drop_table("access_rules")
	op.drop_table("user_roles")
	# ### end Alembic commands ###
